# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Google-SafeBrowsing-UpdateRequest
version:      1.06
version_from: lib/Net/Google/SafeBrowsing/UpdateRequest.pm
installdirs:  site
requires:
    DB_File:                       0
    Digest::MD5:                   0
    English:                       0
    Fcntl:                         0
    fields:                        0
    File::Temp:                    0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    Net::Google::SafeBrowsing::Blocklist: 0
    Test::More:                    0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
